module.exports = {
    USER_CREATE_FAILED: 0,
    USER_CREATED_SUCCESSFULLY: 1,
    USER_ALREADY_EXISTED: 2,
    CHATROOM_CREATED_SUCCESSFULLY: 3,
    CHATROOM_CREATE_FAILED: 4,
    CHATMESSAGE_CREATE_FAILED:5,
    CHATMESSAGE_CREATED_SUCCESSFULLY:6,
    POST_CREATE_FAILED: 7,
    POST_CREATED_SUCCESSFULLY: 8,
    CATEGORIES_CREATE_FAILED: 9,
    CATEGORIES_CREATED_SUCCESSFULLY:10
}